version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: academic-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: academic_platform
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - academic-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: academic-rabbitmq
    restart: always
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - academic-network

  api-gateway:
    build:
      context: .
      dockerfile: apps/api-gateway/Dockerfile
    container_name: api-gateway
    restart: always
    depends_on:
      - postgres
      - rabbitmq
    environment:
      PORT: 3000

      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_NAME: academic_platform

      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
    ports:
      - '3000:3000'
    networks:
      - academic-network

  notification-service:
    build:
      context: .
      dockerfile: apps/notification-service/Dockerfile
    container_name: notification-service
    restart: always
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
    ports:
      - '3001:3001'
    networks:
      - academic-network

  audit-service:
    build:
      context: .
      dockerfile: apps/audit-service/Dockerfile
    container_name: audit-service
    restart: always
    depends_on:
      - rabbitmq
      - postgres
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_NAME: academic_platform

      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
    ports:
      - '3002:3002'
    networks:
      - academic-network

volumes:
  postgres_data:
  rabbitmq_data:

networks:
  academic-network:
    driver: bridge